# Generated by Django 5.1.2 on 2024-11-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('path', models.CharField(db_index=True, max_length=2048)),
                ('referrer', models.CharField(blank=True, db_index=True, max_length=2048, null=True)),
                ('device', models.CharField(db_index=True, max_length=100)),
                ('browser', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'pageviews',
            },
        ),
    ]
