# Generated by Django 5.1.2 on 2024-11-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('path', models.TextField(db_index=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('device', models.TextField()),
                ('browser', models.TextField()),
                ('country', models.TextField()),
                ('language', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pageviews',
            },
        ),
    ]
