# Generated by Django 5.1.2 on 2024-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='project',
            field=models.CharField(db_index=True, default='default', max_length=255),
        ),
    ]
