# Generated by Django 5.1.2 on 2024-11-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_pageview_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
