# Generated by Django 5.1.2 on 2024-11-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_websites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Websites',
            new_name='Website',
        ),
    ]
