# Generated by Django 5.1.2 on 2024-11-04 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_websites_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.website'),
            preserve_default=False,
        ),
    ]
