# Generated by Django 5.1.2 on 2024-11-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_pageview_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='project',
        ),
    ]
