# Generated by Django 5.1.2 on 2024-11-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_pageview_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='browser',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='device',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='hash_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='path',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='referrer',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['website', 'timestamp', 'path', 'referrer'], name='pageviews_website_df4128_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['website', 'timestamp', 'hash_id'], name='pageviews_website_ddaf8c_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['website', 'timestamp', 'country'], name='pageviews_website_bc418d_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['website', 'timestamp', 'device'], name='pageviews_website_7614dd_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['website', 'timestamp', 'browser'], name='pageviews_website_dd800a_idx'),
        ),
    ]
