# Generated by Django 5.1.2 on 2024-11-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_pageview_pageviews_website_53b17f_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pageview',
            name='pageviews_website_df4128_idx',
        ),
        migrations.RemoveIndex(
            model_name='pageview',
            name='pageviews_website_ddaf8c_idx',
        ),
    ]
